version: '2'

volumes:
  go_path:

services:
  moxie:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    ports:
      - "8080:8080"
    entrypoint: go run moxie.go

  http_one:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    entrypoint: go run tools/httpecho.go
    command: --port 8001

  http_two:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    entrypoint: go run tools/httpecho.go
    command: --port 8002

  http_three:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    entrypoint: go run tools/httpecho.go
    command: --port 8000

  websocket_one:
    build:
      context: tools/websocket_echo_server
      dockerfile: Dockerfile
