version: '2'

volumes:
  go_path:

services:
  moxie:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    ports:
      - "8080:8080"
    entrypoint: go run moxie.go

  defaulthost:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    entrypoint: go run tools/echohttpd.go

  backendone:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    entrypoint: go run tools/echohttpd.go
    command: --port 8001

  backendtwo:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie
    entrypoint: go run tools/echohttpd.go
    command: --port 8002

