version: '2'

volumes:
  go_path:

services:
  dev:
    build:
      context: .
      dockerfile: environments/Dockerfile.dev
    volumes:
      - go_path:/go
      - .:/go/src/github.com/placer14/moxie

  production:
    build:
      context: .
      dockerfile: environments/Dockerfile.prod
    ports:
      - "8080:8080"

